version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_dbname}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api_server:
    build:
      dockerfile: Dockerfile
      context: server
    ports:
      - "8000:8000"


  tg_bot:
    build:
      dockerfile: Dockerfile
      context: bot
    depends_on:
      db:
        condition: service_started
    environment:
      PYTHONUNBUFFERED: 1
      DB_dbname: ${DB_dbname}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      TG_TOKEN: ${TG_TOKEN}
      BACKEND_ADDRESS: http://api_server:8000
volumes:
  db_data:

